const $=id=>document.getElementById(id);let array=[],running=false;
document.querySelectorAll(".tab").forEach(tab=>tab.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".module").forEach(x=>x.classList.remove("active"));tab.classList.add("active");$(tab.dataset.target).classList.add("active")}));

const complexities={bubble:["O(n)","O(n²)","O(n²)"],selection:["O(n²)","O(n²)","O(n²)"],insertion:["O(n)","O(n²)","O(n²)"],merge:["O(n log n)","O(n log n)","O(n log n)"],quick:["O(n log n)","O(n log n)","O(n²)"]};
function updateComplexity(){const c=complexities[$("sort-algo").value];["comp-best","comp-avg","comp-worst"].forEach((id,i)=>$(id).textContent=c[i])}
$("sort-algo").addEventListener("change",updateComplexity);$("sort-speed").addEventListener("input",()=>$("speed-val").textContent=$("sort-speed").value);
$("array-size").addEventListener("input",()=>{if(!running)generateArray()});$("btn-generate").addEventListener("click",()=>{if(!running)generateArray()});
function delay(){return [220,100,38,10,0][+$("sort-speed").value-1]}function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function stats(){ $("stat-unsorted").textContent=array.filter((_,i)=>!sorted.has(i)).length;$("stat-sorted").textContent=sorted.size;$("stat-comparisons").textContent=comps;$("stat-swaps").textContent=moves}
let sorted=new Set(),comps=0,moves=0;
function color(i,s){const e=$("sorting-container").children[i];if(e)e.className="book "+s}
function render(){const box=$("sorting-container");box.innerHTML="";const w=Math.max(3,Math.floor(900/array.length)-2);array.forEach(v=>{const e=document.createElement("div");e.className="book";e.style.height=v+"%";e.style.width=w+"px";box.appendChild(e)})}
function generateArray(){const n=+$("array-size").value;$("size-val").textContent=n;array=Array.from({length:n},()=>Math.floor(Math.random()*86)+10);sorted=new Set;comps=moves=0;render();stats()}
async function compare(a,b){comps++;stats();color(a,"compare");if(b!==a)color(b,"compare");await sleep(delay())}
async function swap(a,b){if(a===b)return;[array[a],array[b]]=[array[b],array[a]];const x=$("sorting-container").children[a],y=$("sorting-container").children[b];x.style.height=array[a]+"%";y.style.height=array[b]+"%";moves++;stats();await sleep(delay())}
async function bubble(){for(let end=array.length-1;end>0;end--){let changed=false;for(let j=0;j<end;j++){await compare(j,j+1);if(array[j]>array[j+1]){await swap(j,j+1);changed=true}color(j,"");color(j+1,"")}sorted.add(end);color(end,"sorted");if(!changed)break}}
async function selection(){for(let i=0;i<array.length-1;i++){let m=i;for(let j=i+1;j<array.length;j++){await compare(m,j);if(array[j]<array[m])m=j;color(j,"")}await swap(i,m);sorted.add(i);color(i,"sorted")}}
async function insertion(){for(let i=1;i<array.length;i++){let j=i;while(j>0){await compare(j-1,j);if(array[j-1]<=array[j])break;await swap(j-1,j);j--}for(let k=0;k<=i;k++)color(k,"sorted");sorted.add(i);}}
async function merge(){async function rec(l,r){if(l>=r)return;let m=(l+r)>>1;await rec(l,m);await rec(m+1,r);let left=array.slice(l,m+1),right=array.slice(m+1,r+1),i=0,j=0,k=l;while(i<left.length&&j<right.length){await compare(k,k);array[k]=left[i]<=right[j]?left[i++]:right[j++];$("sorting-container").children[k].style.height=array[k]+"%";moves++;stats();k++}while(i<left.length){array[k]=left[i++];$("sorting-container").children[k].style.height=array[k]+"%";moves++;stats();k++}while(j<right.length){array[k]=right[j++];$("sorting-container").children[k].style.height=array[k]+"%";moves++;stats();k++}}await rec(0,array.length-1)}
async function quick(){async function part(l,r){let p=array[r],i=l;for(let j=l;j<r;j++){await compare(j,r);if(array[j]<p){await swap(i,j);i++}}await swap(i,r);return i}async function rec(l,r){if(l>=r)return;let p=await part(l,r);await rec(l,p-1);await rec(p+1,r)}await rec(0,array.length-1)}
$("btn-sort").addEventListener("click",async()=>{if(running)return;running=true;["btn-sort","btn-generate","array-size","sort-algo"].forEach(id=>$(id).disabled=true);try{sorted.clear();comps=moves=0;const a=$("sort-algo").value;if(a==="bubble")await bubble();else if(a==="selection")await selection();else if(a==="insertion")await insertion();else if(a==="merge")await merge();else await quick();sorted=new Set(array.map((_,i)=>i));array.forEach((_,i)=>color(i,"sorted"));stats()}finally{running=false;["btn-sort","btn-generate","array-size","sort-algo"].forEach(id=>$(id).disabled=false)}});

const ROWS=21,COLS=45;let grid=[],start={r:10,c:7},target={r:10,c:37},drag="none";
function initGrid(){const box=$("grid-container");box.innerHTML="";grid=[];for(let r=0;r<ROWS;r++){let row=[];for(let c=0;c<COLS;c++){let n={r,c,wall:false,prev:null};row.push(n);let e=document.createElement("div");e.className="node";e.id=`n-${r}-${c}`;if(r===start.r&&c===start.c)e.classList.add("node-start");if(r===target.r&&c===target.c)e.classList.add("node-end");e.onmousedown=x=>down(x,r,c);e.onmouseenter=()=>enter(r,c);box.appendChild(e)}grid.push(row)}}
function el(r,c){return $(`n-${r}-${c}`)}function down(e,r,c){if(r===start.r&&c===start.c)drag="start";else if(r===target.r&&c===target.c)drag="end";else{drag="wall";toggle(r,c)}e.preventDefault()}function enter(r,c){if(!drag||running)return;if(drag==="wall")toggle(r,c);else{if((r===target.r&&c===target.c)||(r===start.r&&c===start.c))return;let old=drag==="start"?start:target;el(old.r,old.c).classList.remove(drag==="start"?"node-start":"node-end");if(drag==="start")start={r,c};else target={r,c};grid[r][c].wall=false;el(r,c).classList.remove("node-wall");el(r,c).classList.add(drag==="start"?"node-start":"node-end")}}document.addEventListener("mouseup",()=>drag="none");
function toggle(r,c){if((r===start.r&&c===start.c)||(r===target.r&&c===target.c))return;grid[r][c].wall=!grid[r][c].wall;el(r,c).classList.toggle("node-wall",grid[r][c].wall)}
function clearTrace(){grid.flat().forEach(n=>{n.prev=null;el(n.r,n.c).classList.remove("node-visited","node-path")});$("nodes-explored").textContent=0;$("path-length").textContent=0}
$("btn-clear-path").onclick=()=>{if(!running)clearTrace()};$("btn-clear-board").onclick=()=>{if(!running){start={r:10,c:7};target={r:10,c:37};initGrid();clearTrace()}};$("path-speed").oninput=()=>$("path-speed-val").textContent=$("path-speed").value;function pdelay(){return [90,45,18,5,0][+$("path-speed").value-1]}
function neighbors(n){return [[n.r-1,n.c],[n.r,n.c+1],[n.r+1,n.c],[n.r,n.c-1]].filter(([r,c])=>r>=0&&r<ROWS&&c>=0&&c<COLS).map(([r,c])=>grid[r][c])}
async function search(type){clearTrace();const s=grid[start.r][start.c],t=grid[target.r][target.c],front=[s],seen=new Set([`${s.r},${s.c}`]);let head=0,found=null,explored=0;while(type==="bfs"?head<front.length:front.length){const cur=type==="bfs"?front[head++]:front.pop();if(cur===t){found=cur;break}if(cur!==s){el(cur.r,cur.c).classList.add("node-visited");$("nodes-explored").textContent=++explored;await sleep(pdelay())}let ns=neighbors(cur);if(type==="dfs")ns.reverse();for(const n of ns){const k=`${n.r},${n.c}`;if(!n.wall&&!seen.has(k)){seen.add(k);n.prev=cur;front.push(n)}}}if(found){let path=[],c=found;while(c){path.unshift(c);c=c.prev}$("path-length").textContent=Math.max(0,path.length-1);for(let i=1;i<path.length-1;i++){el(path[i].r,path[i].c).classList.remove("node-visited");el(path[i].r,path[i].c).classList.add("node-path");await sleep(Math.min(35,pdelay()))}}}
$("btn-start-path").onclick=async()=>{if(running)return;running=true;["btn-start-path","btn-clear-path","btn-clear-board"].forEach(id=>$(id).disabled=true);try{await search($("path-algo").value)}finally{running=false;["btn-start-path","btn-clear-path","btn-clear-board"].forEach(id=>$(id).disabled=false)}};generateArray();updateComplexity();initGrid();
